version: '3.5'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - sample

  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - sample

networks:
    sample: